package net.singularity.jetta.compiler.backend

import net.singularity.jetta.compiler.frontend.ir.*
import net.singularity.jetta.compiler.frontend.resolve.*
import org.objectweb.asm.ClassWriter
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes
import org.objectweb.asm.Type
import org.objectweb.asm.commons.LocalVariablesSorter

class LambdaGenerator(
    private val className: String,
    private val lambda: Lambda,
    private val moduleSpaceName: String,
) {
    private val capturedVariables = lambda.capturedVariables()

    fun generate(): CompilationResult {
        val cw = ClassWriter(ClassWriter.COMPUTE_MAXS or ClassWriter.COMPUTE_FRAMES)
        cw.visit(
            Constants.JVM_TARGET_VERSION,
            Opcodes.ACC_PUBLIC,
            className,
            null,
            Type.getInternalName(Object::class.java),
            arrayOf(JETTA_FUNCTION_INTERNAL_NAME),
        )
        lambda.position?.let { cw.visitSource(it.filename, null) }

        val init = cw.visitMethod(
            Opcodes.ACC_PUBLIC,
            "<init>",
            mkLambdaInitDescriptor(capturedVariables),
            null,
            null
        )
        generateFields(cw)
        generateInit(init)

        // Public SAM bridge: apply(Object[]) -> Object. Unpacks the array,
        // unboxes / casts to typed-apply's parameter types, calls the private
        // typed apply, then boxes the result.
        val samApply = cw.visitMethod(
            Opcodes.ACC_PUBLIC,
            JETTA_FUNCTION_SAM_NAME,
            JETTA_FUNCTION_SAM_DESCRIPTOR,
            null,
            null
        )
        generateSamBridge(samApply)

        // Private typed apply: holds the actual lambda body. Generated by
        // FunctionGenerator the same way ordinary function bodies are.
        val typedDesc = mkTypedApplyDescriptor()
        val typed = LocalVariablesSorter(
            Opcodes.ACC_PRIVATE,
            typedDesc,
            cw.visitMethod(
                Opcodes.ACC_PRIVATE,
                TYPED_APPLY_NAME,
                typedDesc,
                null,
                null
            )
        )
        generateTypedApply(typed)
        return CompilationResult(className, cw.toByteArray())
    }

    private fun generateFields(cw: ClassWriter) {
        capturedVariables.forEach {
            cw.visitField(
                Opcodes.ACC_PRIVATE,
                it.name,
                it.type!!.toJvmType(),
                null,
                null
            )
        }
    }

    private fun generateInit(mv: MethodVisitor) {
        mv.visitVarInsn(Opcodes.ALOAD, 0)
        mv.visitMethodInsn(
            Opcodes.INVOKESPECIAL,
            "java/lang/Object",
            "<init>",
            "()V",
            false
        )
        capturedVariables.forEach {
            mv.visitVarInsn(Opcodes.ALOAD, 0)
            generateLoadVar(mv, it, capturedVariables, false, null)
            mv.visitFieldInsn(Opcodes.PUTFIELD, className, it.name, it.type!!.toJvmType())
        }
        mv.visitInsn(Opcodes.RETURN)
        mv.visitMaxs(1, 1)
    }

    private fun generateTypedApply(mv: LocalVariablesSorter) {
        val generator = FunctionGenerator(mv, lambda, false, className, moduleSpaceName)
        generator.generate()
    }

    private fun generateSamBridge(mv: MethodVisitor) {
        mv.visitVarInsn(Opcodes.ALOAD, 0) // this
        lambda.params.forEachIndexed { index, variable ->
            mv.visitVarInsn(Opcodes.ALOAD, 1) // args
            generateLoadInt(mv, index)
            mv.visitInsn(Opcodes.AALOAD)
            val type = variable.type as? GroundedType
            if (type != null && !isReferenceLike(type)) {
                unboxIfNeeded(mv, type)
            } else {
                val jvmType = variable.type!!.toJvmType()
                if (jvmType != "Ljava/lang/Object;") {
                    mv.visitTypeInsn(Opcodes.CHECKCAST, jvmType.drop(1).dropLast(1))
                }
            }
        }
        mv.visitMethodInsn(
            Opcodes.INVOKEVIRTUAL,
            className,
            TYPED_APPLY_NAME,
            mkTypedApplyDescriptor(),
            false
        )
        boxIfNeeded(mv, lambda.returnType as? GroundedType)
        mv.visitInsn(Opcodes.ARETURN)
        // COMPUTE_MAXS/FRAMES handles stack sizing.
        mv.visitMaxs(0, 0)
    }

    private fun mkTypedApplyDescriptor(): String {
        val sb = StringBuilder()
        sb.append('(')
        lambda.params.forEach { sb.append(it.type!!.toJvmType()) }
        sb.append(')')
        sb.append(lambda.returnType!!.toJvmType())
        return sb.toString()
    }

    private fun isReferenceLike(type: GroundedType): Boolean = when (type) {
        GroundedType.INT, GroundedType.LONG,
        GroundedType.DOUBLE, GroundedType.BOOLEAN -> false
        else -> true
    }

    companion object {
        const val JETTA_FUNCTION_INTERNAL_NAME = "net/singularity/jetta/runtime/functions/JettaFunction"
        const val JETTA_FUNCTION_SAM_NAME = "apply"
        const val JETTA_FUNCTION_SAM_DESCRIPTOR = "([Ljava/lang/Object;)Ljava/lang/Object;"
        const val TYPED_APPLY_NAME = "applyTyped"
    }
}

private fun generateLoadInt(mv: MethodVisitor, value: Int) {
    when (value) {
        0 -> mv.visitInsn(Opcodes.ICONST_0)
        1 -> mv.visitInsn(Opcodes.ICONST_1)
        2 -> mv.visitInsn(Opcodes.ICONST_2)
        3 -> mv.visitInsn(Opcodes.ICONST_3)
        4 -> mv.visitInsn(Opcodes.ICONST_4)
        5 -> mv.visitInsn(Opcodes.ICONST_5)
        else -> mv.visitIntInsn(Opcodes.BIPUSH, value)
    }
}
